# Generated by Django 5.0.9 on 2024-10-07 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTpContato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255, unique=True)),
                ('inativo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_config-tpContato',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('inativo', models.BooleanField(default=False)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cidades.cidade')),
            ],
            options={
                'db_table': 'tb_aluno',
            },
        ),
        migrations.CreateModel(
            name='AlunoContato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contato', models.CharField(max_length=255)),
                ('detalhe', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='alunos.aluno')),
                ('tipoContato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.configtpcontato')),
            ],
            options={
                'db_table': 'tb_aluno-contato',
            },
        ),
    ]
