# Generated by Django 2.1.15 on 2024-09-18 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(max_length=7)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('inativo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_aluno',
            },
        ),
        migrations.CreateModel(
            name='AlunoContato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contato', models.CharField(max_length=255)),
                ('detalhe', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Aluno')),
            ],
            options={
                'db_table': 'tb_aluno_contato',
            },
        ),
        migrations.CreateModel(
            name='ConfigTpContato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255, unique=True)),
                ('inativo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_config_tp_contato',
            },
        ),
        migrations.AddField(
            model_name='alunocontato',
            name='tipo_contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.ConfigTpContato'),
        ),
    ]
