# Generated by Django 2.1.15 on 2024-09-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_auto_20240919_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cidades.Cidade'),
        ),
    ]
