# Generated by Django 2.1.15 on 2024-09-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacao',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('siglaExame', models.CharField(max_length=50)),
                ('duracao', models.IntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('inativo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_certificacao',
            },
        ),
        migrations.CreateModel(
            name='Certificador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('siglaCertificador', models.CharField(max_length=3)),
                ('inativo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_certificador',
            },
        ),
        migrations.AddField(
            model_name='certificacao',
            name='idCertificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificacoes.Certificador'),
        ),
    ]
