# Generated by Django 2.1.15 on 2024-09-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificador',
            name='siglaCertificador',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='certificacao',
            name='duracao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='certificacao',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
