# Generated by Django 2.1.15 on 2024-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacoes', '0002_auto_20240924_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificador',
            name='siglaCertificador',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
