# Generated by Django 5.0.9 on 2024-10-01 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'tb_uf',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cidades.estado')),
            ],
            options={
                'db_table': 'tb_uf-cidade',
            },
        ),
    ]
