# Generated by Django 2.1.15 on 2024-09-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cidade',
            table='tb_uf-cidade',
        ),
    ]
